title: <p align="center"> Suqi Huang </p>

logo: "images/ResumePic.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/D_SuqiHuang.pdf">Resume</a>
  </p>
   
  <p align="justify">
  Master of Urban Analytics at HKU
  <br><br>
  Hi! I'm a graduate student at the University of Hong Kong. Passionate about using data science, geospatial technologies, and development methodologies to facilitate climate change mitigation, public policy making and business development.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
