title: <p align="center"> Suqi Huang </p>

logo: "images/ResumePic.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/D_SuqiHuang.pdf">Resume</a>
  </p>
   
  <p align="justify">
  Master of Urban Analytics at HKU
  <br><br>
  Skilled in using data science, geospatial technologies, and development methodologies to facilitate climate change mitigation, public policy making and business development. More than 2 years of experience in assessing the value of urban renewal projects, while building business insight through real estate project cooperation.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
