title: Suqi Huang # your name (or website title) here

logo: "images/ResumePic_2.jpg" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/CV_SuqiHuang.pdf">Resume</a>
  </p>
   
  <p align="justify">
  Master of Urban Analytics at HKU, Expected Graduation: November 2022
  <br><br>
  Hi! I'm a graduate student at the University of Hong Kong, interested in exploring creative ways to leverage public sector data. Passionate about creating equitable solutions to address climate change, economic inequality, and transportation accessibility gaps.
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
